# Generated by Django 4.2.5 on 2023-09-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empname',
            field=models.CharField(db_column='ename', max_length=100),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='emp',
        ),
    ]
